### ISSUE TITLE
entity-sensor in separate module?

### ISSUE THREAD

**Issue by jie-dong** [netmod-wg/entity#10]
In conf-call We discussed whether the sensor-mib objects could be moved to a separate module, which augments the generic entity module.  
Or we need to solve the overlap between entPhySensorOperStatus and entStateOper?

**Comment by mbj4668** [comment]
jie-dong notifications@github.com wrote:

> In conf-call We discussed whether the sensor-mib objects could be
> moved to a separate module, which augments the generic entity
> module.    

Yes, but then I thought that if we do this for sensor objects, we
should probably do the same for the state objects.  And there were
really no real reason for doing the separation, so I kept everything
in one module.  We can discuss this further later with the WG.

> Or we need to solve the overlap between entPhySensorOperStatus and
> entStateOper?

Maybe not.

/martin

**Comment by abierman** [comment]
Hi,

I have been working on this today.
I agree to keep the objects together.
I think the sensor stuff might need a redesign to use a union leaf,
instead of an integer + scale + precision.

Maybe not now, but an open issue

Andy

**Comment by mbj4668** [comment]
Since there has been no more discussion around this, we should keep the objects together.
