### ISSUE TITLE
IANA entity YANG Module

### ISSUE THREAD

**Issue by mbj4668** [netmod-wg/entity#7]
Move all physical class identities to iana-entity YANG module.  This module needs to be maintained by IANA just like  IANA-ENTITY-MIB.

**Comment by dromasca** [comment]
so the iana YANG and SMI modules need to be kept in sync - maybe they should be made one registry?

**Comment by mbj4668** [comment]
dromasca notifications@github.com wrote:

> so the iana YANG and SMI modules need to be kept in sync - maybe they
> should be made one registry?

Yes that would be ideal.  Just like both IANAifType-MIB and the
iana-if-type YANG module are generated (manually by IANA) from the
common registry "ifType Definitions".

/martin
